### PR TITLE
Added screenshot utility/flameshot stuff at _index.md

### PR DESCRIPTION
**Pull request by ardishco-the-great**
programs like flameshot won't capture both of your screens most of the time, so I thought adding a small tutorial to make them work on multimon setups to the FAQ would be helpful.

There is also the matter of flameshot being extremely slow on selection on Hyprland, which I have a workaround for, which might be worth adding but it is a little hacky, so I didn't put it here and it might not even be relevant soon because the workaround already requires compiling a PR (which I would have to create a tutorial for and might not be worth it since it might get merged) and installing a package from the AUR if the user is on Arch Linux. (and so on)

I didn't think it would be appropriate to add it here but if you think I should, I would be happy to add it to this PR.

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]
uhh k, it sucks but ok

**Comment by ardishco-the-great** [comment]
> 

What can I do to improve it? I'd love to know how If you think it could be improved.
Or do you mean that it's a little unnecessary?

**Comment by vaxerski** [comment]
I meant flameshot sucks

**Comment by ardishco-the-great** [comment]
Oh okay.

**Pull request merged**
