### PR TITLE
hyprlock: document float support for layoutxy

### PR DESCRIPTION
**Pull request by PaideiaDilemma**
Someone asked for support for this and then I realized it already works nicely.

### CODE REVIEW

**Comment by vaxerski** [comment]
ref https://github.com/hyprwm/hyprlock/pull/591

**Comment by vaxerski** [comment]
right? or wrong? I am sick I might be a bit funky

**Comment by PaideiaDilemma** [comment]
@vaxerski 
No this is already how it works. Not related to https://github.com/hyprwm/hyprlock/pull/591.

That PR has no wiki MR yet, wanted to wait for feedback.
If you preferred, I can start to always open wiki mrs in parallel.

**Comment by vaxerski** [comment]
ye woudl be nice

**Review by vaxerski — APPROVED** [review]

**Pull request merged**
