### PR TITLE
Update FreeBSD dependencies

### PR DESCRIPTION
**Pull request by jbeich**

### CODE REVIEW

**Comment by vaxerski** [comment]
how is jq a hard dep?

**Comment by jbeich** [comment]
```
$ meson setup hyprland_build hyprland
The Meson build system
Version: 1.1.0
Source dir: /tmp/hyprland
Build dir: /tmp/hyprland_build
Build type: native build

hyprland/meson.build:2:12: ERROR: Program or command 'jq' not found or not executable

A full log can be found at /tmp/hyprland_build/meson-logs/meson-log.txt
```

**Comment by vaxerski** [comment]
huh. Meson. Maybe @fufexan did something. Fair.

**Review by vaxerski — APPROVED** [review]
thanks!

**Comment by fufexan** [comment]
> huh. Meson. Maybe @fufexan did something. Fair.

Yeah, remember when we implemented version reading from `props.json`?

**Comment by vaxerski** [comment]
right.

**Comment by eli-schwartz** [comment]
> Yeah, remember when we implemented version reading from `props.json`?

Sounds incredibly painful, why make it into json instead of just a version file containing a single line with the version?

**Comment by fufexan** [comment]
> > Yeah, remember when we implemented version reading from `props.json`?
> 
> Sounds incredibly painful, why make it into json instead of just a version file containing a single line with the version?

I don't remember the real reason, but I think we wanted to be future proof in case another variable needed to be added.

**Comment by eli-schwartz** [comment]
Has this turned out to be a problem in practice? What other information might need to be read into the build system itself?

**Comment by fufexan** [comment]
> Has this turned out to be a problem in practice? What other information might need to be read into the build system itself?

No. We just over engineered it seems. 🤷‍♂️

**Pull request merged**
