### PR TITLE
Add mention about possibility to start hypridle, hyprpaper and hyprpolkit with system services.

### PR DESCRIPTION
**Pull request by izmyname**
Wording may not be the best, but I think it's worth to mention systemd services, as an alternative to exec-once=. Anyway, suggestions are welcome.

### CODE REVIEW

**Review by fufexan — CHANGES_REQUESTED** [review]
> If you start Hyprland with a systemd service

I don't think this is necessary. I don't start hyprland as a systemd service but still use user services for hypr* apps.

**Comment by izmyname** [comment]
From my experience, it's only possible to start systemd services from hyprland.conf, in your case as Hyprland, itself, doesn't provide `graphical-session.target`, required for them to be enabled on startup.

This was the reason why I started to work on hyprland-session.service integration, in the first place.

**Comment by fufexan** [comment]
Ok, makes sense then. Still, I think the wording should be "if you start Hyprland **as** a systemd service".

**Review by fufexan — APPROVED** [review]
Generally LGTM.

**Pull request merged**
