### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by pechano**
Both Sway and Hyprland can work just fine with VFR, if the monitor is "stepped" into the right refresh rate. I have added instructions on how to do this. It requires a bit of experimenting.

### CODE REVIEW

**Comment by vaxerski** [comment]
what? explain.

**Comment by pechano** [comment]
On my setup (AOC AG27QXP + Radeon 5700XT) I have noticed that adaptive sync can work just fine under Wayland GNOME (using Mutter), but the two wlroots compositors I have tried had issues out of the box. These two being Sway and Hyprland. When I used Sway I figured out (by accident) that if I switched the refresh rates around a few times, I would get rid of the white flashing normally caused by adaptive sync/vfr options. I tried doing it with the Hyprland equivalent commands and it worked. So I just wanted to share it, in case others have the same issue. I have not seen any mention of a solution anywhere.

**Comment by vaxerski** [comment]
please mention it over [here](https://github.com/hyprwm/Hyprland/issues/351) and let others verify this.

**Comment by pechano** [comment]
I have made a post over on the VFR flash issue. Hopefully this method also works for other people. I know it's very hacky, but it may help someone with more knowledge track down the root cause.

**Comment by NotAShelf** [comment]
@pechano is this still relevant?

**Comment by pechano** [comment]
Yeah I get that, no worries. I think the main issue here is that this bug only happens with certain monitors on certain cards, so it is difficult to reproduce at a meaningful scale. I might be one of the only hyprland users with exactly my setup. It would be great if other users who experience flickering were able to experiment a bit.
But I think this is a bug in that will eventually get fixed through wlroots, and not a specific wm. Until then, I will rely on this small script.

**Comment by vaxerski** [comment]
since the thing above got resolved, I see no point in this anymore.

**Pull request closed without merging**
