### PR TITLE
Get rid of the archived awesome-wayland

### PR DESCRIPTION
**Pull request by yavko**

### CODE REVIEW

**Comment by vaxerski** [comment]
why draft

**Comment by yavko** [comment]
> why draft

idk maybe to replace it idk

**Comment by MahouShoujoMivutilde** [comment]
BTW, does anybody knows what happened to it? Like, _why_ is it archived?

I've tried writing to @natpen 's mail, but received no response.

**Comment by vaxerski** [comment]
conflict

**Comment by vaxerski** [comment]
thanks

**Pull request merged**
