### PR TITLE
clarify wording and fix broken links

### PR DESCRIPTION
**Pull request by NotAShelf**
Some moron thought the wording on the wiki was not clear enough.

This hopefully brings the level of """complicated""" sentences to their elementary English level and make it more readable by the general Linux community.

Also closes #85, #92 and #96

### CODE REVIEW

**Comment by NotAShelf** [comment]
side note, lets also close #56 because 1. unnecessary and 2. old and likely outdated

**Comment by NotAShelf** [comment]
Q: have I tested this PR?
A: no, some nerd refuses to let me run a local copy of the backend

**Comment by vaxerski** [comment]
@fufexan can you read this I cba I am laziness

**Review by fufexan — APPROVED** [review]
LGTM

**Comment by fufexan** [comment]
> side note, lets also close #56 because 1. unnecessary and 2. old and likely outdated

I could rebase and update it later, why not.

**Comment by vaxerski** [comment]
slaaaay guurl :nail_care:

**Pull request merged**
