### PR TITLE
make links to wiki entries more consistent

### PR DESCRIPTION
**Pull request by MonAaraj**
Just this PR doesn't improve everything, though. The side-bar also has confusing names for these files, and I think (for at least the configuring section) that they should be changed to the file's name. i.e. change "Start Configuring" to "Master Config" etc.

### CODE REVIEW

**Comment by vaxerski** [comment]
I've deliberately changed them because "basic" and "advanced" made people instantly skip to advanced, because people are idiots.

**Comment by MonAaraj** [comment]
Maybe the names should be "Configuring, part 1" and "Configuring, part 2", i have a feeling that this would urge people to read both parts sequentially.

**Comment by MonAaraj** [comment]
@vaxerski I'd appreciate a review of this when you have time, please

**Comment by fufexan** [comment]
I'm all for this but I think we should split the Master config more.

**Comment by vaxerski** [comment]
master..?

**Comment by fufexan** [comment]
https://github.com/hyprwm/hyprland-wiki/compare/e9697a74c3ced7bd1ea1f1754414acb4fa3bc103...a23fd8881056c37161733442f36fdf9e6a60de1b thoughts please.

**Comment by fufexan** [comment]
This was solved, so I'm closing it.

**Pull request closed without merging**
