### PR TITLE
Clarify alterzorder

### PR DESCRIPTION
**Pull request by Aqa-Ib**
Good info for new users in my opinion.

### CODE REVIEW

**Comment by vaxerski** [comment]
clarifies so much that I don't even understand what you wanted to say there

**Comment by Aqa-Ib** [comment]
I want to make clear that the dispatcher won't work if you try to put a floating window below a tiling window.

**Comment by vaxerski** [comment]
`Modify the window stack order of the active or specified window. Note: this cannot be used to move a floating window behind a tiled one`

**Review by vaxerski — APPROVED** [review]
:+1:

**Comment by Aqa-Ib** [comment]
As you wish. Thanks for your time.

**Pull request merged**
