### PR TITLE
Mention plugin availability in the GURU Gentoo overlay

### PR DESCRIPTION
**Pull request by foopsss**
I've noticed that some plugins can be installed from GURU now, so I added that information.

### CODE REVIEW

**Comment by vaxerski** [comment]
I would advise against, we have `hyprpm`.

**Comment by foopsss** [comment]
I'm aware of `hyprpm`, but, from my short experience on Gentoo it seems that people here also like having the option to install plug-ins for apps using Portage. A good example of this is [Emacs](https://wiki.gentoo.org/wiki/GNU_Emacs#Additional_elisp_packages). Moreover, I think that not every plug-in has updated its documentation to add a `hyprpm` installation method yet, and I don't know if instructions are generic enough that they can be used for every plug-in, since I don't use plug-ins.

However, I don't intend to go against your wishes, so I can just close the MR if desired and add this to the Gentoo wiki page for Hyprland instead.

**Comment by vaxerski** [comment]
well the problem with hyprland plugins is that plugins have to be compiled against the exact version of hyprland you're running. If you update your hyprland but don't recompile plugins, they stop working (or even worse, could crash hyprland)

**Comment by vaxerski** [comment]
I added hyprpm for a reason. All plugins have either a hyprload or a hyprpm manifest, so this shouldnt be an issue. Instructions are generic.

**Pull request closed without merging**
