### PR TITLE
preconfigured setups: remove end-4/dots-hyprland

### PR DESCRIPTION
**Pull request by end-4**
As the author of end-4/dots-hyprland, I feel I cannot maintain it well for now and would like to have it removed from the wiki, at least temporarily, to not cause new users any issues.

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]
thank you for your work in the past!

**Comment by clsty** [comment]
@vaxerski 2 months has passed. After some PRs merged, commits pushed and issues solved in end-4/dots-hyprland (especially [using virtual environment for python](https://github.com/end-4/dots-hyprland/issues/1017) and [using stable Arch package for Hyprland](https://github.com/end-4/dots-hyprland/issues/1080)), now it installs and runs pretty stable and smooth, so I think it's suitable to revert this PR now.

**Comment by vaxerski** [comment]
that would be up to @end-4

**Comment by clsty** [comment]
> that would be up to @end-4

Yeah that makes sense.

@end-4 you can actually be more confident about your project because many major issues complained by users were actually caused by versioning/installation thingy (which should be my responsibility...) but now they are much stabler essentially.

**Comment by end-4** [comment]
Thank you @clsty for your dedication, and I agree. vaxry, can you revert this?

**Comment by fufexan** [comment]
Reverted.

**Comment by vaxerski** [comment]
thanks fuf

**Pull request merged**
