### PR TITLE
Remove ~, replace with full path

### PR DESCRIPTION
**Pull request by DaraghD**
It seems that [wlroots can't](https://github.com/hyprwm/Hyprland/issues/5553) expand the ~ for user home directory, so full path must be used without it.
 pinging @kiecla as they initially wrote it and there may be some misunderstanding, assuming it worked for them when it was wrote.

### CODE REVIEW

**Comment by kiecla** [comment]
I didn't test that set up. If I recall I copied that down from somewhere else. My bad. I leave that variable unset and wlroots will default to the iGPU in that case. This PR is a necessary change to what I wrote.
I might suggest telling the user to put the symlink somewhere user-agnostic, i.e. outside of the home directory, so that on systems with more than one user (probably not many nowadays, especially on hyprland) this works without having to access another user's home directory.
/usr/local is a candidate, but it might depend on distribution. I don't think that change is all that important really as most people are completely unaffected by it.

**Comment by Fxzzi** [comment]
Should also try `$HOME`, that would probably work, idk tho

**Comment by MahouShoujoMivutilde** [comment]
Apparently `$HOME` does work:

Tested via fully exiting Hyprland, and trying to run it from a tty with

```
env = WLR_DRM_DEVICES,$HOME/.config/hypr/card
```

where card is `/home/witch/.config/hypr/card -> /dev/dri/by-path/pci-0000:09:00.0-card`

\- works fine.

Deliberately providing the wrong path, as expected, makes it fail with an error about failing to create the backend, so I know it actually uses the card from the path instead falling back to whatever works.

---

Also, @DaraghD, it says in one section

> run `ls -l /dev/dri/by-path`

but the section right after, about the symlink, uses

> `ln -sf /dev/dri/pci-0000:06:00.0-card ...`

Notice the missing `by-path`.

For me, `/dev/dri` looks like

```
/dev/dri
├── by-path
│   ├── pci-0000:09:00.0-card -> ../card0
│   └── pci-0000:09:00.0-render -> ../renderD128
├── card0
└── renderD128
```

And [here](https://github.com/hyprwm/Hyprland/issues/5553#issuecomment-2050469991) is `by-path` too.

**Comment by DaraghD** [comment]
> Apparently `$HOME` does work:
> 
> Tested via fully exiting Hyprland, and trying to run it from a tty with
> 
> ```
> env = WLR_DRM_DEVICES,$HOME/.config/hypr/card
> ```
> 
> where card is `/home/witch/.config/hypr/card -> /dev/dri/by-path/pci-0000:09:00.0-card`
> 
> - works fine.
> 
> Deliberately providing the wrong path, as expected, makes it fail with an error about failing to create the backend, so I know it actually uses the card from the path instead falling back to whatever works.
> 
> Also, @DaraghD, it says in one section
> 
> > run `ls -l /dev/dri/by-path`
> 
> but the section right after, about the symlink, uses
> 
> > `ln -sf /dev/dri/pci-0000:06:00.0-card ...`
> 
> Notice the missing `by-path`.
> 
> For me, `/dev/dri` looks like
> 
> ```
> /dev/dri
> ├── by-path
> │   ├── pci-0000:09:00.0-card -> ../card0
> │   └── pci-0000:09:00.0-render -> ../renderD128
> ├── card0
> └── renderD128
> ```
> 
> And [here](https://github.com/hyprwm/Hyprland/issues/5553#issuecomment-2050469991) is `by-path` too.

The documentation says explicitly not to use that, however it may be wrong again. I only told the person in the issue to do that to see if it would work as a hack, I couldn't test the other way so couldn't confirm if it worked or not.
Possibly should also change the documentation from /home/user to $HOME, up to whatever the maintainer prefers-  maybe mention both?

**Comment by Fxzzi** [comment]
> change the documentation from /home/user to $HOME, up to whatever the maintainer prefers- maybe mention both?

I'm not a maintainer however I feel leaving just `$HOME` should suffice. I have not seen one circumstance where it's not set, and also allows for portability - e.g. if someone copies dotfiles of another / username changes the config will still work without manually needing to change.

**Comment by MahouShoujoMivutilde** [comment]
> The documentation says explicitly not to use that, however it may be wrong again.

Well it's wrong in that there is to `pci...` thing there at all, because it's in its own subdirectory.

I'm pretty sure `by-path` was just forgotten, because as far as I can tell `/dev/dri` only supposed to contain `cardN`, `render...`, not pci, those are inside `by-path`, from everywhere I can find.

I agree, if $HOME works - no reason not to use it.

**Review by fufexan — APPROVED** [review]

**Pull request merged**
