### PR TITLE
Added a new page under "Useful Utilities", named "USB Automount"

### PR DESCRIPTION
**Pull request by WasteOfO2**
I noticed in my prev PR i made some minor mistakes in MD formatting that i have now fixed

In addition, I have added a small guide for automatically mounting USB mass storage devices

### CODE REVIEW

**Comment by vaxerski** [comment]
ignoring the fact you have literal conflicts, I'd also rather stick this into "other"

**Comment by WasteOfO2** [comment]
sure i will stick this into "other"

what conflicts are u talking abt?

**Comment by vaxerski** [comment]
image

**Comment by WasteOfO2** [comment]
I have 0 recollection of this and have no idea how this came about, will fix right away

**Comment by WasteOfO2** [comment]
All should be good now, review changes and lmk if further changes are needed

also, unrelated to the PR, but did u have a look at the issue i raised? i think the nvidia guide might be misleading

**Comment by vaxerski** [comment]
> also, unrelated to the PR, but did u have a look at the issue i raised? i think the nvidia guide might be misleading

I don't support nvidia, it's all written by volunteers

> ukw, I think we can merge "uncommon tips and tricks", "example configs" and "others" into a "miscellaneous" category, thoughts?

nah

**Pull request merged**
