### PR TITLE
Fix hyprland -> Hyprland on Master Tutorial

### PR DESCRIPTION
**Pull request by Polarzincomfrio**

### CODE REVIEW

**Comment by fufexan** [comment]
Not really necessary, as `hyprland` is a symlink to the `Hyprland` binary.

**Comment by Polarzincomfrio** [comment]
but the `hyprland` and `hyprland -h` command's will never work since the correct one that needs to be ran on the tty is `Hyprland`

**Comment by fufexan** [comment]
Why will it never work? I just tried it and it works.

**Comment by Polarzincomfrio** [comment]
So on your setup, `hyprland` works because of how it’s linked, but on mine, it might not by default. That’s why using `Hyprland` is normally a better practice, since it’s the real command and avoids issues across different setups. 
image

**Comment by fufexan** [comment]
Ok, sure.

**Review by fufexan — APPROVED** [review]

**Pull request merged**
