### PR TITLE
Update Installation.md

### PR DESCRIPTION
**Pull request by shadowmax31**
Needs gcc 13+, I don't know if it changed anything for clang.

https://github.com/hyprwm/Hyprland/pull/3186

### CODE REVIEW

**Comment by fufexan** [comment]
Are you sure it works with `13.0.0`? I've only tried building with `13.2.0`.

**Review by vaxerski — APPROVED** [review]
ok, but clang is also wrong now lel

**Comment by shadowmax31** [comment]
> Are you sure it works with `13.0.0`? I've only tried building with `13.2.0`.

I also only tried with 13.2.0, but I went off of vaxry's comment in the PR

**Comment by vaxerski** [comment]
it's 13.0

**Pull request merged**
