### PR TITLE
add full hypridle example work with hyprlock.

### PR DESCRIPTION
**Pull request by sentakuhm**
added full hypridle example work with hyprlock for better understanding.

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
since this is meant as an example, the notify-send stuff in general {} can be removed for better readability

**Comment by sentakuhm** [comment]
> since this is meant as an example, the notify-send stuff in general {} can be removed for better readability

done.

**Review by vaxerski — APPROVED** [review]
lgtm, thanks!

**Comment by dpredovic** [comment]
The example could be expanded to avoid questions/issues. It doesn't lock before suspend, connects to dbus or shows how to lock/suspend manually.

I'd suggest something like:
```
general {
    lock_cmd = pidof hyprlock || hyprlock # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key twice to turn on the display
}

# turn off keyboard backlight
#listener { 
#    timeout = 30 
#    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 
#    on-resume = brightnessctl -rd rgb:kbd_backlight
#}

# set monitor backlight to minimum
listener {
    timeout = 60
    on-timeout = brightnessctl -s set 0 
    on-resume = brightnessctl -r
}

# lock
listener {
    timeout = 120 
    on-timeout = loginctl lock-session 
}

# turn display off
listener {
    timeout = 150
    on-timeout = hyprctl dispatch dpms off
}

# suspend
listener {
    timeout = 180
    on-timeout = systemctl suspend
}
```

You also most probably want to have something like this in hyprland.conf:
```
exec-once = hypridle
...
misc {
  mouse_move_enables_dpms = true
  key_press_enables_dpms = true
  ...
}
...
bind = $mainMod, L, exec, loginctl lock-session 
bind = $mainMod ALT, L, exec, systemctl suspend 
```

**Comment by vaxerski** [comment]
that'd be better off for the hypridle page

**Comment by dpredovic** [comment]
Yes, but the documentation is very... Abstract? "notify-send" for every option doesn't give users much of a direction of how is it supposed to be integrated with rest of the system. 

If you look at github dotfiles repos containing hypridle, you will hardly find one where it's integrated "properly", so I'd say that even powerusers have troubles with full config. I needed hours to come up with a config that works in all edge cases. :)

**Comment by sentakuhm** [comment]
@vaxerski so, are we going to add @dpredovic's example?.

**Comment by vaxerski** [comment]
idk feel free to mr

**Pull request merged**
