### PR TITLE
Update NVIDIA cursor:no_hardware_cursors

### PR DESCRIPTION
**Pull request by Agent00Ming**

### CODE REVIEW

**Comment by vaxerski** [comment]
it shouldnt crash, though. That's a bug if it does.

**Comment by Agent00Ming** [comment]
https://github.com/hyprwm/Hyprland/issues/5964 user reports here

**Comment by vaxerski** [comment]
bug should be fixed

**Comment by vaxerski** [comment]
this MR could still be merged if you remove the crash mentions cuz I forgot to replace the env with the new config keyword xD

**Comment by Agent00Ming** [comment]
yeah just a sec

**Comment by Agent00Ming** [comment]
that should do it

**Review by vaxerski — APPROVED** [review]
thanks!

**Pull request merged**
