### PR TITLE
Add install instructions for Ximper Linux

### PR DESCRIPTION
**Pull request by fiersik**
Packages of the Hyprland ecosystem are available in Ximper Linux.

It is planned to create a separate build based on this window manager in the near future.

### CODE REVIEW

**Comment by vaxerski** [comment]
I am unsure if ximper is significant enough to be worth putting into the already cluttered installation combo

**Comment by X1mper** [comment]
> I am unsure if ximper is significant enough to be worth putting into the already cluttered installation combo
Isn't it important for hyprland developers to work with the community?
I think every distribution is important

**Review by fufexan — APPROVED** [review]

**Comment by fufexan** [comment]
The installation combo may be cluttered but we can split it into multiple pages.

**Comment by vaxerski** [comment]
fair neough

**Pull request merged**
